export const answers = {
  decisions: [
    'Päätös on selkeä. Sen sisältö tarkentuu myöhemmin.',
    'Edetään määrätietoisesti kohti seuraavaa keskustelua.',
    'Tässä vaiheessa tärkeintä on säilyttää päätöksenteon tuntuma.',
    'Valitse rohkeasti se vaihtoehto, jonka joku muu hyväksyy.',
    'Suosittelen hallittua siirtymää asian äärelle.',
    'Älä päätä vielä. Epävarmuus on strategista liikkumavaraa.',
    'Tämä vaatii tiekartan. Tie ei ole vielä tarpeen.',
    'Kyllä, mutta riittävän ylätasolla myös ei.',
    'Oikea suunta löytyy, kun määrittelemme oikean uudelleen.',
    'Otetaan tästä koppi ja asetetaan se varovasti takaisin.',
    'Perusta työryhmä. Päätös ei saa jäädä vain tekemättä.',
    'Nyt tarvitaan rohkeutta odottaa lisäselvitystä.',
    'Kaikki vaihtoehdot ovat hyviä, kun vastuu on jaettu.',
    'Priorisoi kokonaisuus. Yksityiskohdat sisältävät ongelman.',
    'Tee päätös, joka näyttää hyvältä seuraavassa kalvossa.',
    'Asia on selvä. Selvitetään seuraavaksi, mikä asia.',
    'Emme lykkää päätöstä. Kypsytämme päätöksentekokulttuuria.',
    'Lähdetään liikkeelle siitä, että palataan lähtökohtiin.',
    'Ratkaisu on olemassa. Sen etsiminen ei kuulu tähän vaiheeseen.',
    'Vie asia eteenpäin. Eteenpäin on jonkun muun pöytä.',
    'Ratkaisevaa on tunnistaa se päätös, joka mahdollistaa seuraavan tason ajattelun.',
    'Kun suunta on sisäisesti kirkas, vaihtoehdot alkavat järjestyä sen ympärille.',
    'Suosittelen etenemistä, jossa kokonaisuus ohjaa kokonaisuuden kannalta olennaista.',
    'Tässä kohtaa meidän on uskallettava luottaa yhteisen näkemyksen kantavuuteen.',
    'Päätöksen laatu syntyy siitä tilasta, josta käsin päätös tehdään.',
    'Nyt rakennamme valmiutta siihen hetkeen, jossa valmius muuttuu mahdollisuudeksi.',
    'Kyse on ennen kaikkea siitä, millaisen suhteen otat tulevaan suuntaasi.',
    'Olemme tunnistaneet tarpeen vahvistaa tunnistettujen tarpeiden yhteistä ymmärrystä.',
    'Tämä vaihtoehto palvelee juuri sitä tulevaisuutta, jota kohti olemme suuntautumassa.',
    'Anna ratkaisulle lupa nousta siitä kokonaisuudesta, jonka osana kysymys elää.',
    'Oikea ajoitus löytyy, kun päätöksenteko ja päätösvalmius kohtaavat samalla tasolla.',
    'Varmuus kasvaa, kun sitoudut siihen suuntaan, johon olet valmis sitoutumaan.',
    'Meidän tehtävämme on mahdollistaa ne edellytykset, joita mahdollistaminen vaatii.',
    'Näen tässä vahvan perustan seuraavan vaiheen perustan rakentamiselle.',
    'Päätös kannattaa ankkuroida siihen tahtotilaan, jonka päätös tekee näkyväksi.',
    'Tämä on se kohta, jossa tietoinen valinta alkaa valita tulevaisuuttasi.',
    'Yhteinen linjaus antaa meille suunnan yhteisen suunnan linjaamiseen.',
    'Kun päästät irti vastauksen tarpeesta, päätös saa tilaa vahvistua.',
    'Seuraavassa vaiheessa syvennämme sitä selkeyttä, jota tämä vaihe on avannut.',
    'Luotan täysin siihen, että etenemisemme tarkentuu etenemisen myötä.',
  ],
  career: [
    'Potentiaalisi on tunnistettu. Se korvaa palkankorotuksen.',
    'Seuraava askel on ottaa askel kohti seuraavaa askelta.',
    'Ole korvaamaton. Silloin et pääse nykyisestä tehtävästäsi.',
    'Näkyvyytesi kasvaa, kun teet muidenkin työt.',
    'Urapolkusi on yksilöllinen. Siksi sitä ei ole piirretty.',
    'Titteli on vain sana. Tässä sinulle kolme lisää.',
    'Kasva roolissasi. Roolin budjetti pysyy ennallaan.',
    'Olet valmis seuraavalle tasolle. Taso ei ole valmis sinulle.',
    'Verkostoidu ihmisten kanssa, jotka myös verkostoituvat.',
    'Tuo rohkeasti oma äänesi esiin. Mielellään johdon sanoin.',
    'Kehityskeskustelu oli erinomainen. Kehitystä ei edellytetä meiltä.',
    'Ota omistajuutta. Omistus jää luonnollisesti meille.',
    'Sinulla on lupa loistaa sovitun näkyvyysbudjetin rajoissa.',
    'Työsi puhuu puolestaan. Harmi, ettei se ole johtoryhmässä.',
    'Ajattele isosti. Resursointi hoidetaan pienesti.',
    'Et ole jumissa. Olet strategisesti vakiintunut.',
    'Mukavuusalueesi ulkopuolella on lisää samoja tehtäviä.',
    'Urasi suunta on ylöspäin. Organisaatiokaavio käännetään.',
    'Johtajuus alkaa siitä, että kutsut kiirettä intohimoksi.',
    'Jatka samaan malliin. Se on palautteemme koko sisältö.',
    'Seuraava uratasosi odottaa sitä versiota sinusta, joka jo toimii sen tasolta käsin.',
    'Ammatillinen läpimurto alkaa, kun oma kasvusi tunnistaa sinut sen mahdollistajaksi.',
    'Sinun on ensin omistettava se arvo, jonka haluat muiden tunnistavan omaksesi.',
    'Valmennukseni ydin on auttaa sinua löytämään oma tapasi löytää oma ytimesi.',
    'Kun asemoit osaamisesi uudelleen, suhteesi omaan asemaasi alkaa uudistua.',
    'Et tarvitse lisää näyttöjä. Tarvitset uuden suhteen siihen, mitä näyttö sinulle merkitsee.',
    'Vaikuttavuutesi kasvaa siinä suhteessa, jossa annat kasvullesi luvan vaikuttaa.',
    'Olemme sitoutuneet tukemaan polkusi seuraavan vaiheen mahdollisuuksien tunnistamista.',
    'Menestyjät tunnistavat hetken, jossa oma potentiaali pyytää uudenlaista tunnistamista.',
    'Roolisi tulevaisuus rakentuu siitä, miten tulevaisuutesi ottaa oman roolinsa.',
    'Johtajuus on kykyä kannatella sitä tilaa, jossa johtajuus voi tulla näkyväksi.',
    'Sinussa on jo kaikki se, minkä seuraava kehitysvaiheesi tulee sinulle avaamaan.',
    'Uusi asemasi alkaa siitä hetkestä, kun lakkaat toimimasta vanhan asemasi kautta.',
    'Tämä menetelmä tuo osaamiseesi sen ulottuvuuden, jota et vielä osaa nimetä.',
    'Asiantuntijuus syvenee, kun siirryt tekemisen tasolta tekemisen merkityksen tasolle.',
    'Nyt on aika ottaa haltuun se kasvutarina, joka tekee sinusta oman kasvusi suunnannäyttäjän.',
    'Mahdollisuutesi ovat jo olemassa. Yhteinen työmme tekee niiden olemassaolosta näkyvää.',
    'Urasi seuraava vaihe ei kysy mitä osaat, vaan mistä käsin osaamisesi nousee.',
    'Lupaan, että tämän prosessin jälkeen katsot omaa potentiaaliasi prosessin uudelta tasolta.',
    'Kun sisäinen johtajuutesi vahvistuu, ulkoinen urapolkusi alkaa vastata sen kutsuun.',
  ],
  money: [
    'Budjetti on ennen kaikkea yhteinen mielentila.',
    'Rahaa ei puutu. Se on vain kohdennettu muualle.',
    'Katso kulua investointina, niin se tuntuu kalliimmalta.',
    'Taloutesi kaipaa visiota. Kate voi odottaa.',
    'Kassavirta on liikkeessä. Lähinnä poispäin.',
    'Säästä strategisesti asioista, jotka eivät näy johdolle.',
    'Tämä ei ole menoerä. Tämä on tulevaisuustarina.',
    'Euro on hyvä mittari, mutta tunnelma näyttää paremmalta.',
    'Tuotto-odotus on vahva. Tuottoa ei ole kuultu.',
    'Budjetoi optimismia. Se ei näy velkana.',
    'Keskity arvonluontiin. Arvon saaja päätetään myöhemmin.',
    'Taloudellinen liikkumavara löytyy esityksen marginaaleista.',
    'Numerot ovat vain yksi näkökulma numeroihin.',
    'Emme ylittäneet budjettia. Budjetti alitti visiomme.',
    'Kannattavuus on matkalla. Aikataulu on luottamuksellinen.',
    'Ostovoimasi on nyt ketterämpi. Se mahtuu pienempään tilaan.',
    'Puhutaan mieluummin mahdollisuuksista kuin summista.',
    'Kulut ovat konkreettisia. Hyödyt ovat strategisia.',
    'Tase kaipaa tasapainoa. Aloitetaan fontista.',
    'Talous näyttää hyvältä, kun vertailukohta valitaan oikein.',
    'Vauraus alkaa siitä, että annat vaurauden mahdollisuudelle tilaa omassa ajattelussasi.',
    'Rahavirta seuraa sitä arvon virtaa, jonka olet valmis tunnistamaan omaksesi.',
    'Taloudellinen vapaus on ensin suhde vapauteen ja vasta sitten suhde talouteen.',
    'Menetelmäni auttaa avaamaan ne kasvun tasot, joilla seuraava kasvusi jo odottaa.',
    'Kun sisäinen arvosi asettuu kohdalleen, ulkoinen arvonmuodostus löytää uuden tason.',
    'Rahan energia vahvistuu, kun taloudellinen tahtotilasi on linjassa vastaanottamisen kanssa.',
    'Olemme siirtymässä vaiheeseen, jossa talouden potentiaali alkaa tukea potentiaalin taloutta.',
    'Runsaus ei kysy mistä aloitat, vaan millaisesta lähtökohdasta olet valmis aloittamaan.',
    'Kestävä kasvu rakentuu kasvun kestävyyttä vahvistaville sisäisille edellytyksille.',
    'Seuraava tulotasosi tarvitsee sinulta ennen kaikkea seuraavan tason tulotietoisuutta.',
    'Taloudellinen läpimurto on luonnollinen seuraus läpimurron mahdollistavasta ajattelusta.',
    'Tässä ohjelmassa emme tavoittele numeroita, vaan suhdetta numeroiden takana olevaan arvoon.',
    'Arvon kasvattaminen alkaa siitä, että kasvu itsessään tunnistetaan arvoksi.',
    'Avaa itsellesi mahdollisuus siihen taloudelliseen mahdollisuuteen, joka on jo avautumassa.',
    'Vaurauden uusi taso syntyy, kun vanha käsityksesi tasosta ei enää määritä vaurauttasi.',
    'Olen nähnyt tämän toistuvasti: talous muuttuu, kun suhde taloudelliseen muutokseen muuttuu.',
    'Sinulle on tarjolla enemmän, kun olet sisäisesti valmis siihen, mitä enemmän tarkoittaa.',
    'Tavoitteemme on vahvistaa arvopohjaa, jolle tuleva arvon vahvistuminen voi rakentua.',
    'Anna taloudelliselle suunnallesi lupa laajentua kohti laajempaa taloudellista suuntaa.',
    'Tämä kokonaisuus avaa sinulle ne vaurauden periaatteet, jotka tekevät vauraudesta mahdollista.',
  ],
  relationships: [
    'Kuuntele aidosti. Valmistele samalla oma puheenvuorosi.',
    'Suhteenne kaipaa yhteistä tilannekuvaa ja erillisiä kalentereita.',
    'Tunteet ovat arvokasta palautetta. Kirjataan ne tiedoksi.',
    'Olkaa samalla sivulla. Sisällöstä voidaan sopia myöhemmin.',
    'Rakkaus on yhteinen matka ilman nimettyä projektipäällikköä.',
    'Avoin keskustelu toimii parhaiten ennalta sovituilla vastauksilla.',
    'Anna toiselle tilaa. Mielellään toisessa kokouksessa.',
    'Sitoutuminen alkaa yhteisestä määritelmäpalaverista.',
    'Teillä ei ole ristiriitaa. Teillä on rinnakkaiset totuudet.',
    'Luottamus rakentuu teoista. Aloitetaan kuitenkin esityksellä.',
    'Yhteinen suunta on tärkeämpi kuin se, haluaako kumpikaan sinne.',
    'Nosta kissa pöydälle. Perusta sille ohjausryhmä.',
    'Odotukset kannattaa sanoittaa niin, ettei niihin voi tarttua.',
    'Empatia on sitä, että nyökkäät ennen omaa asiaasi.',
    'Palataan tunteisiisi seuraavassa kvartaalissa.',
    'Suhteen tila on vakaa. Liikettäkään ei ole havaittu.',
    'Yhteistyö toimii, kun molemmat joustavat sinun suuntaasi.',
    'Älä etsi syyllisiä. Nimeä vastuuhenkilö.',
    'Olette molemmat oikeassa. Tämä ei muuta mitään.',
    'Läheisyys vaatii läsnäoloa. Etäosallistuminenkin hyväksytään.',
    'Aito yhteys syntyy tilassa, jossa yhteyden syntymiselle on annettu aito mahdollisuus.',
    'Suhteenne seuraava taso alkaa siitä, miten suhtaudutte seuraavan tason mahdollisuuteen.',
    'Kohtaaminen syvenee, kun molemmat tulevat nähdyiksi oman kohtaamisensa äärellä.',
    'Teidän on ensin löydettävä yhteinen tapa löytää se, mikä teille on yhteistä.',
    'Luottamuksen vahvistaminen edellyttää luottamusta sen vahvistumisen edellytyksiin.',
    'Rakkauden tila avautuu, kun annat omalle avoimuudellesi luvan ottaa tilaa.',
    'Valmennuksessa rakennamme yhteyttä siihen yhteyteen, jonka haluatte yhdessä rakentaa.',
    'Kun kuuntelet kuuntelemisesi lähtökohtia, toiselle avautuu uudenlainen kuulluksi tulemisen tila.',
    'Yhteinen tulevaisuus tarvitsee teiltä yhteistä suhdetta siihen, mitä tulevaisuus voi olla.',
    'Läheisyys ei ole etäisyyden vastakohta, vaan uusi tapa olla suhteessa etäisyyteen.',
    'Tunne saa merkityksensä siitä merkityksestä, jonka kohtaaminen sille mahdollistaa.',
    'Vuorovaikutuksenne muuttuu, kun muutatte suhdettanne siihen, mikä välillänne vaikuttaa.',
    'Sinut voidaan kohdata vasta siltä tasolta, jolta olet valmis tulemaan kohdattavaksi.',
    'Yhdessä kasvaminen alkaa oman kasvun ja yhteisen kasvun välisen yhteyden tunnistamisesta.',
    'Anna suhteelle se suunta, jossa sen oma suunta voi vähitellen tulla näkyväksi.',
    'Meidän on nyt kannateltava sitä yhteistä tilaa, joka kannattelee teitä molempia.',
    'Syvempi ymmärrys alkaa siitä, että ymmärrätte syvenemisen merkityksen uudella tavalla.',
    'Tässä prosessissa yhteinen matkanne löytää uuden suhteen omaan yhteisyyteensä.',
    'Lupaan teille uuden näkökulman siihen, miten uudet näkökulmat voivat lähentää teitä.',
    'Kun yhteyden esteet nähdään yhteyden mahdollisuuksina, yhteys alkaa mahdollistua.',
  ],
  life: [
    'Luota prosessiin. Prosessi luottaa siihen, ettet kysy.',
    'Elämälläsi on suunta. Sitä ei ole vielä viestitty.',
    'Ole tässä hetkessä. Seuraava on jo myöhässä.',
    'Tasapaino löytyy, kun kaikki osa-alueet ovat yhtä kesken.',
    'Et ole eksyksissä. Kartoitat vaihtoehtoisia reittejä.',
    'Muutos alkaa sinusta. Resurssit eivät.',
    'Nauti matkasta. Määränpää poistettiin strategiasta.',
    'Hyvinvointisi on meille tärkeää. Tässä linkki kyselyyn.',
    'Unelmoi isosti ja raportoi pienetkin poikkeamat.',
    'Merkitys syntyy tekemisestä. Tekeminen syntyy kalenterikutsusta.',
    'Tämäkin on kasvun paikka. Kasvualustana toimii epämukavuus.',
    'Onnellisuus on asenne. Olosuhteet eivät ole kommentoineet.',
    'Pysähdy kuuntelemaan itseäsi. Varaa ensin vapaa aika.',
    'Elämä ei ole suoritus. Se on jatkuva kehityshanke.',
    'Kaikki järjestyy organisaatiouudistuksessa.',
    'Tarkoitus löytyy arjesta, kun arki nimetään missioksi.',
    'Sinä riität. Tavoitteita nostetaan silti.',
    'Huominen on mahdollisuus siirtää tätä vielä eteenpäin.',
    'Kokonaiskuva on hallussa. Elämä tapahtuu yksityiskohdissa.',
    'Universumi on kuullut sinut. Pyyntösi on käsittelyjonossa.',
    'Paras versiosi odottaa sitä päätöstä, jolla annat itsellesi luvan olla matkalla sitä kohti.',
    'Elämäsi muuttuu, kun se tapa, jolla suhtaudut elämäsi muuttumiseen, alkaa muuttua.',
    'Täyttymys löytyy siltä tasolta, jolla et enää tarvitse vanhan tasosi käsitystä täyttymyksestä.',
    'Tämä hetki sisältää kaiken sen, mitä seuraava hetkesi tarvitsee tullakseen mahdolliseksi.',
    'Ohjelmani ei anna sinulle vastauksia. Se avaa sinut vastauksen mahdollistavalle tilalle.',
    'Sisäinen tasapaino syntyy, kun oma keskuksesi löytää tasapainoisen suhteen sisäisyyteesi.',
    'Olet juuri siinä vaiheessa, jonka kautta seuraava vaiheesi voi tulla sinulle näkyväksi.',
    'Salli oman polkusi avautua siitä kohdasta, jossa avautuminen tuntuu sinulle omalta.',
    'Merkityksellinen elämä rakentuu merkityksen äärelle palaamisen tietoisesta mahdollistamisesta.',
    'Kaikki tarvitsemasi on jo sinussa. Prosessimme auttaa sinua tarvitsemaan sitä uudella tavalla.',
    'Kun luovut vanhasta kasvutarinastasi, kasvusi saa tilaa kertoa sinulle uuden tarinan.',
    'Muutos on jo alkanut sillä tasolla, jolla olet valmis tunnistamaan sen alkaneeksi.',
    'Elämänlaatusi nousee, kun oma tietoisuutesi alkaa tunnistaa laadun uudella tasolla.',
    'Tämä on kutsu astua siihen tilaan, jossa oma kutsumuksesi voi kutsua sinua eteenpäin.',
    'Et tarvitse valmista suunnitelmaa, vaan valmiutta siihen, mitä suunnitelmallisuus sinussa avaa.',
    'Lupaan sinulle matkan, jonka merkityksen ymmärrät vasta oman ymmärryksesi syventyessä.',
    'Hyvinvointi vahvistuu, kun annat vahvistumiselle hyvinvointiasi tukevan merkityksen.',
    'Seuraava läpimurtosi alkaa siitä, että tunnistat tämän hetken osaksi läpimurtosi alkua.',
    'Oma totuutesi löytyy siitä tilasta, jossa et enää etsi sitä vanhan totuutesi ehdoilla.',
    'Kun olet valmis vastaanottamaan elämäsi, elämäsi on valmis vastaamaan valmiuteesi.',
  ],
};

export function drawAnswer(topic, previous, random = Math.random) {
  const choices = answers[topic].filter(answer => answer !== previous);
  return choices[Math.floor(random() * choices.length)];
}

// Require several fast reversals, so a tap, scroll or one drag is not a shake.
export function createShakeDetector(threshold, reversalsNeeded = 3) {
  let direction = 0;
  let reversals = 0;
  let lastTime = -Infinity;
  return (delta, now) => {
    if (Math.abs(delta) < threshold) return false;
    if (now - lastTime > 650) { direction = 0; reversals = 0; }
    const next = Math.sign(delta);
    if (direction && next !== direction) reversals++;
    direction = next;
    lastTime = now;
    if (reversals < reversalsNeeded) return false;
    direction = 0;
    reversals = 0;
    return true;
  };
}
